#!/bin/bash

arguments=(
    # Automatically generated with "generateLaunchSh.js"
	"LOG_LEVEL;None;Enum"
	"CONFIG;None;Unicode"
	"IP;None;Unicode"
	"PORT;None;Int"
	"PORT_RETRIES;None;Int"
	"SOCK;None;Unicode"
	"SOCK_MODE;None;Unicode"
	"TRANSPORT;None;CaselessStrEnum"
	"KEYFILE;None;Unicode"
	"CERTFILE;None;Unicode"
	"CLIENT_CA;None;Unicode"
	"NOTEBOOK_DIR;None;Unicode"
	"BROWSER;None;Unicode"
	"PYLAB;None;Unicode"
	"GATEWAY_URL;None;Unicode"
	"HELP_ALL;None;Boolean"
	"DEBUG;None;Boolean"
	"SHOW_CONFIG;None;Boolean"
	"SHOW_CONFIG_JSON;None;Boolean"
	"GENERATE_CONFIG;None;Boolean"
	"NO_BROWSER;None;Boolean"
	"PYLAB;None;Boolean"
	"NO_MATHJAX;None;Boolean"
	"ALLOW_ROOT;None;Boolean"
	"AUTORELOAD;None;Boolean"
	"SCRIPT;None;Boolean"
	"NO_SCRIPT;None;Boolean"
	"BROWSER;None;Boolean"
	"APPLICATION_LOG_DATEFMT;Application;Unicode"
	"APPLICATION_LOG_FORMAT;Application;Unicode"
	"APPLICATION_LOG_LEVEL;Application;Enum"
	"APPLICATION_SHOW_CONFIG;Application;Bool"
	"APPLICATION_SHOW_CONFIG_JSON;Application;Bool"
	"JUPYTER_APP_ANSWER_YES;JupyterApp;Bool"
	"JUPYTER_APP_CONFIG_FILE;JupyterApp;Unicode"
	"JUPYTER_APP_CONFIG_FILE_NAME;JupyterApp;Unicode"
	"JUPYTER_APP_GENERATE_CONFIG;JupyterApp;Bool"
	"JUPYTER_APP_LOG_DATEFMT;JupyterApp;Unicode"
	"JUPYTER_APP_LOG_FORMAT;JupyterApp;Unicode"
	"JUPYTER_APP_LOG_LEVEL;JupyterApp;Enum"
	"JUPYTER_APP_SHOW_CONFIG;JupyterApp;Bool"
	"JUPYTER_APP_SHOW_CONFIG_JSON;JupyterApp;Bool"
	"NOTEBOOK_APP_ALLOW_CREDENTIALS;NotebookApp;Bool"
	"NOTEBOOK_APP_ALLOW_ORIGIN;NotebookApp;Unicode"
	"NOTEBOOK_APP_ALLOW_ORIGIN_PAT;NotebookApp;Unicode"
	"NOTEBOOK_APP_ALLOW_PASSWORD_CHANGE;NotebookApp;Bool"
	"NOTEBOOK_APP_ALLOW_REMOTE_ACCESS;NotebookApp;Bool"
	"NOTEBOOK_APP_ALLOW_ROOT;NotebookApp;Bool"
	"NOTEBOOK_APP_ANSWER_YES;NotebookApp;Bool"
	"NOTEBOOK_APP_AUTHENTICATE_PROMETHEUS;NotebookApp;Bool"
	"NOTEBOOK_APP_AUTORELOAD;NotebookApp;Bool"
	"NOTEBOOK_APP_BASE_PROJECT_URL;NotebookApp;Unicode"
	"NOTEBOOK_APP_BASE_URL;NotebookApp;Unicode"
	"NOTEBOOK_APP_BROWSER;NotebookApp;Unicode"
	"NOTEBOOK_APP_CERTFILE;NotebookApp;Unicode"
	"NOTEBOOK_APP_CLIENT_CA;NotebookApp;Unicode"
	"NOTEBOOK_APP_CONFIG_FILE;NotebookApp;Unicode"
	"NOTEBOOK_APP_CONFIG_FILE_NAME;NotebookApp;Unicode"
	"NOTEBOOK_APP_CONFIG_MANAGER_CLASS;NotebookApp;Type"
	"NOTEBOOK_APP_CONTENTS_MANAGER_CLASS;NotebookApp;TypeFromClasses"
	"NOTEBOOK_APP_COOKIE_SECRET;NotebookApp;Bytes"
	"NOTEBOOK_APP_COOKIE_SECRET_FILE;NotebookApp;Unicode"
	"NOTEBOOK_APP_CUSTOM_DISPLAY_URL;NotebookApp;Unicode"
	"NOTEBOOK_APP_DEFAULT_URL;NotebookApp;Unicode"
	"NOTEBOOK_APP_DISABLE_CHECK_XSRF;NotebookApp;Bool"
	"NOTEBOOK_APP_ENABLE_MATHJAX;NotebookApp;Bool"
	"NOTEBOOK_APP_FILE_TO_RUN;NotebookApp;Unicode"
	"NOTEBOOK_APP_GENERATE_CONFIG;NotebookApp;Bool"
	"NOTEBOOK_APP_IGNORE_MINIFIED_JS;NotebookApp;Bool"
	"NOTEBOOK_APP_IOPUB_DATA_RATE_LIMIT;NotebookApp;Float"
	"NOTEBOOK_APP_IOPUB_MSG_RATE_LIMIT;NotebookApp;Float"
	"NOTEBOOK_APP_IP;NotebookApp;Unicode"
	"NOTEBOOK_APP_KERNEL_MANAGER_CLASS;NotebookApp;Type"
	"NOTEBOOK_APP_KERNEL_SPEC_MANAGER_CLASS;NotebookApp;Type"
	"NOTEBOOK_APP_KEYFILE;NotebookApp;Unicode"
	"NOTEBOOK_APP_LOG_DATEFMT;NotebookApp;Unicode"
	"NOTEBOOK_APP_LOG_FORMAT;NotebookApp;Unicode"
	"NOTEBOOK_APP_LOG_JSON;NotebookApp;Bool"
	"NOTEBOOK_APP_LOG_LEVEL;NotebookApp;Enum"
	"NOTEBOOK_APP_LOGIN_HANDLER_CLASS;NotebookApp;Type"
	"NOTEBOOK_APP_LOGOUT_HANDLER_CLASS;NotebookApp;Type"
	"NOTEBOOK_APP_MATHJAX_CONFIG;NotebookApp;Unicode"
	"NOTEBOOK_APP_MATHJAX_URL;NotebookApp;Unicode"
	"NOTEBOOK_APP_MAX_BODY_SIZE;NotebookApp;Int"
	"NOTEBOOK_APP_MAX_BUFFER_SIZE;NotebookApp;Int"
	"NOTEBOOK_APP_MIN_OPEN_FILES_LIMIT;NotebookApp;Int"
	"NOTEBOOK_APP_NOTEBOOK_DIR;NotebookApp;Unicode"
	"NOTEBOOK_APP_OPEN_BROWSER;NotebookApp;Bool"
	"NOTEBOOK_APP_PASSWORD;NotebookApp;Unicode"
	"NOTEBOOK_APP_PASSWORD_REQUIRED;NotebookApp;Bool"
	"NOTEBOOK_APP_PORT;NotebookApp;Int"
	"NOTEBOOK_APP_PORT_RETRIES;NotebookApp;Int"
	"NOTEBOOK_APP_PYLAB;NotebookApp;Unicode"
	"NOTEBOOK_APP_QUIT_BUTTON;NotebookApp;Bool"
	"NOTEBOOK_APP_RATE_LIMIT_WINDOW;NotebookApp;Float"
	"NOTEBOOK_APP_RERAISE_SERVER_EXTENSION_FAILURES;NotebookApp;Bool"
	"NOTEBOOK_APP_SESSION_MANAGER_CLASS;NotebookApp;Type"
	"NOTEBOOK_APP_SHOW_CONFIG;NotebookApp;Bool"
	"NOTEBOOK_APP_SHOW_CONFIG_JSON;NotebookApp;Bool"
	"NOTEBOOK_APP_SHUTDOWN_NO_ACTIVITY_TIMEOUT;NotebookApp;Int"
	"NOTEBOOK_APP_SOCK;NotebookApp;Unicode"
	"NOTEBOOK_APP_SOCK_MODE;NotebookApp;Unicode"
	"NOTEBOOK_APP_TERMINALS_ENABLED;NotebookApp;Bool"
	"NOTEBOOK_APP_TOKEN;NotebookApp;Unicode"
	"NOTEBOOK_APP_TRUST_XHEADERS;NotebookApp;Bool"
	"NOTEBOOK_APP_USE_REDIRECT_FILE;NotebookApp;Bool"
	"NOTEBOOK_APP_WEBBROWSER_OPEN_NEW;NotebookApp;Int"
	"NOTEBOOK_APP_WEBSOCKET_COMPRESSION_OPTIONS;NotebookApp;Any"
	"NOTEBOOK_APP_WEBSOCKET_URL;NotebookApp;Unicode"
	"CONNECTION_FILE_MIXIN_CONNECTION_FILE;ConnectionFileMixin;Unicode"
	"CONNECTION_FILE_MIXIN_CONTROL_PORT;ConnectionFileMixin;Int"
	"CONNECTION_FILE_MIXIN_HB_PORT;ConnectionFileMixin;Int"
	"CONNECTION_FILE_MIXIN_IOPUB_PORT;ConnectionFileMixin;Int"
	"CONNECTION_FILE_MIXIN_IP;ConnectionFileMixin;Unicode"
	"CONNECTION_FILE_MIXIN_SHELL_PORT;ConnectionFileMixin;Int"
	"CONNECTION_FILE_MIXIN_STDIN_PORT;ConnectionFileMixin;Int"
	"CONNECTION_FILE_MIXIN_TRANSPORT;ConnectionFileMixin;CaselessStrEnum"
	"KERNEL_MANAGER_AUTORESTART;KernelManager;Bool"
	"KERNEL_MANAGER_CONNECTION_FILE;KernelManager;Unicode"
	"KERNEL_MANAGER_CONTROL_PORT;KernelManager;Int"
	"KERNEL_MANAGER_HB_PORT;KernelManager;Int"
	"KERNEL_MANAGER_IOPUB_PORT;KernelManager;Int"
	"KERNEL_MANAGER_IP;KernelManager;Unicode"
	"KERNEL_MANAGER_SHELL_PORT;KernelManager;Int"
	"KERNEL_MANAGER_SHUTDOWN_WAIT_TIME;KernelManager;Float"
	"KERNEL_MANAGER_STDIN_PORT;KernelManager;Int"
	"KERNEL_MANAGER_TRANSPORT;KernelManager;CaselessStrEnum"
	"SESSION_BUFFER_THRESHOLD;Session;Int"
	"SESSION_CHECK_PID;Session;Bool"
	"SESSION_COPY_THRESHOLD;Session;Int"
	"SESSION_DEBUG;Session;Bool"
	"SESSION_DIGEST_HISTORY_SIZE;Session;Int"
	"SESSION_ITEM_THRESHOLD;Session;Int"
	"SESSION_KEY;Session;CBytes"
	"SESSION_KEYFILE;Session;Unicode"
	"SESSION_PACKER;Session;DottedObjectName"
	"SESSION_SESSION;Session;CUnicode"
	"SESSION_SIGNATURE_SCHEME;Session;Unicode"
	"SESSION_UNPACKER;Session;DottedObjectName"
	"SESSION_USERNAME;Session;Unicode"
	"MULTI_KERNEL_MANAGER_DEFAULT_KERNEL_NAME;MultiKernelManager;Unicode"
	"MULTI_KERNEL_MANAGER_KERNEL_MANAGER_CLASS;MultiKernelManager;DottedObjectName"
	"MULTI_KERNEL_MANAGER_SHARED_CONTEXT;MultiKernelManager;Bool"
	"MAPPING_KERNEL_MANAGER_BUFFER_OFFLINE_MESSAGES;MappingKernelManager;Bool"
	"MAPPING_KERNEL_MANAGER_CULL_BUSY;MappingKernelManager;Bool"
	"MAPPING_KERNEL_MANAGER_CULL_CONNECTED;MappingKernelManager;Bool"
	"MAPPING_KERNEL_MANAGER_CULL_IDLE_TIMEOUT;MappingKernelManager;Int"
	"MAPPING_KERNEL_MANAGER_CULL_INTERVAL;MappingKernelManager;Int"
	"MAPPING_KERNEL_MANAGER_DEFAULT_KERNEL_NAME;MappingKernelManager;Unicode"
	"MAPPING_KERNEL_MANAGER_KERNEL_INFO_TIMEOUT;MappingKernelManager;Float"
	"MAPPING_KERNEL_MANAGER_KERNEL_MANAGER_CLASS;MappingKernelManager;DottedObjectName"
	"MAPPING_KERNEL_MANAGER_ROOT_DIR;MappingKernelManager;Unicode"
	"MAPPING_KERNEL_MANAGER_SHARED_CONTEXT;MappingKernelManager;Bool"
	"KERNEL_SPEC_MANAGER_ENSURE_NATIVE_KERNEL;KernelSpecManager;Bool"
	"KERNEL_SPEC_MANAGER_KERNEL_SPEC_CLASS;KernelSpecManager;Type"
	"CONTENTS_MANAGER_ALLOW_HIDDEN;ContentsManager;Bool"
	"CONTENTS_MANAGER_CHECKPOINTS;ContentsManager;Instance"
	"CONTENTS_MANAGER_CHECKPOINTS_CLASS;ContentsManager;Type"
	"CONTENTS_MANAGER_FILES_HANDLER_CLASS;ContentsManager;Type"
	"CONTENTS_MANAGER_PRE_SAVE_HOOK;ContentsManager;Any"
	"CONTENTS_MANAGER_ROOT_DIR;ContentsManager;Unicode"
	"CONTENTS_MANAGER_UNTITLED_DIRECTORY;ContentsManager;Unicode"
	"CONTENTS_MANAGER_UNTITLED_FILE;ContentsManager;Unicode"
	"CONTENTS_MANAGER_UNTITLED_NOTEBOOK;ContentsManager;Unicode"
	"FILE_MANAGER_MIXIN_USE_ATOMIC_WRITING;FileManagerMixin;Bool"
	"FILE_CONTENTS_MANAGER_ALLOW_HIDDEN;FileContentsManager;Bool"
	"FILE_CONTENTS_MANAGER_CHECKPOINTS;FileContentsManager;Instance"
	"FILE_CONTENTS_MANAGER_CHECKPOINTS_CLASS;FileContentsManager;Type"
	"FILE_CONTENTS_MANAGER_DELETE_TO_TRASH;FileContentsManager;Bool"
	"FILE_CONTENTS_MANAGER_FILES_HANDLER_CLASS;FileContentsManager;Type"
	"FILE_CONTENTS_MANAGER_POST_SAVE_HOOK;FileContentsManager;Any"
	"FILE_CONTENTS_MANAGER_PRE_SAVE_HOOK;FileContentsManager;Any"
	"FILE_CONTENTS_MANAGER_ROOT_DIR;FileContentsManager;Unicode"
	"FILE_CONTENTS_MANAGER_SAVE_SCRIPT;FileContentsManager;Bool"
	"FILE_CONTENTS_MANAGER_UNTITLED_DIRECTORY;FileContentsManager;Unicode"
	"FILE_CONTENTS_MANAGER_UNTITLED_FILE;FileContentsManager;Unicode"
	"FILE_CONTENTS_MANAGER_UNTITLED_NOTEBOOK;FileContentsManager;Unicode"
	"FILE_CONTENTS_MANAGER_USE_ATOMIC_WRITING;FileContentsManager;Bool"
	"NOTEBOOK_NOTARY_ALGORITHM;NotebookNotary;Enum"
	"NOTEBOOK_NOTARY_DATA_DIR;NotebookNotary;Unicode"
	"NOTEBOOK_NOTARY_DB_FILE;NotebookNotary;Unicode"
	"NOTEBOOK_NOTARY_SECRET;NotebookNotary;Bytes"
	"NOTEBOOK_NOTARY_SECRET_FILE;NotebookNotary;Unicode"
	"NOTEBOOK_NOTARY_STORE_FACTORY;NotebookNotary;Callable"
	"ASYNC_MULTI_KERNEL_MANAGER_DEFAULT_KERNEL_NAME;AsyncMultiKernelManager;Unicode"
	"ASYNC_MULTI_KERNEL_MANAGER_KERNEL_MANAGER_CLASS;AsyncMultiKernelManager;DottedObjectName"
	"ASYNC_MULTI_KERNEL_MANAGER_SHARED_CONTEXT;AsyncMultiKernelManager;Bool"
	"ASYNC_MAPPING_KERNEL_MANAGER_BUFFER_OFFLINE_MESSAGES;AsyncMappingKernelManager;Bool"
	"ASYNC_MAPPING_KERNEL_MANAGER_CULL_BUSY;AsyncMappingKernelManager;Bool"
	"ASYNC_MAPPING_KERNEL_MANAGER_CULL_CONNECTED;AsyncMappingKernelManager;Bool"
	"ASYNC_MAPPING_KERNEL_MANAGER_CULL_IDLE_TIMEOUT;AsyncMappingKernelManager;Int"
	"ASYNC_MAPPING_KERNEL_MANAGER_CULL_INTERVAL;AsyncMappingKernelManager;Int"
	"ASYNC_MAPPING_KERNEL_MANAGER_DEFAULT_KERNEL_NAME;AsyncMappingKernelManager;Unicode"
	"ASYNC_MAPPING_KERNEL_MANAGER_KERNEL_INFO_TIMEOUT;AsyncMappingKernelManager;Float"
	"ASYNC_MAPPING_KERNEL_MANAGER_KERNEL_MANAGER_CLASS;AsyncMappingKernelManager;DottedObjectName"
	"ASYNC_MAPPING_KERNEL_MANAGER_ROOT_DIR;AsyncMappingKernelManager;Unicode"
	"ASYNC_MAPPING_KERNEL_MANAGER_SHARED_CONTEXT;AsyncMappingKernelManager;Bool"
	"GATEWAY_KERNEL_MANAGER_BUFFER_OFFLINE_MESSAGES;GatewayKernelManager;Bool"
	"GATEWAY_KERNEL_MANAGER_CULL_BUSY;GatewayKernelManager;Bool"
	"GATEWAY_KERNEL_MANAGER_CULL_CONNECTED;GatewayKernelManager;Bool"
	"GATEWAY_KERNEL_MANAGER_CULL_IDLE_TIMEOUT;GatewayKernelManager;Int"
	"GATEWAY_KERNEL_MANAGER_CULL_INTERVAL;GatewayKernelManager;Int"
	"GATEWAY_KERNEL_MANAGER_DEFAULT_KERNEL_NAME;GatewayKernelManager;Unicode"
	"GATEWAY_KERNEL_MANAGER_KERNEL_INFO_TIMEOUT;GatewayKernelManager;Float"
	"GATEWAY_KERNEL_MANAGER_KERNEL_MANAGER_CLASS;GatewayKernelManager;DottedObjectName"
	"GATEWAY_KERNEL_MANAGER_ROOT_DIR;GatewayKernelManager;Unicode"
	"GATEWAY_KERNEL_MANAGER_SHARED_CONTEXT;GatewayKernelManager;Bool"
	"GATEWAY_KERNEL_SPEC_MANAGER_ENSURE_NATIVE_KERNEL;GatewayKernelSpecManager;Bool"
	"GATEWAY_KERNEL_SPEC_MANAGER_KERNEL_SPEC_CLASS;GatewayKernelSpecManager;Type"
	"GATEWAY_CLIENT_AUTH_TOKEN;GatewayClient;Unicode"
	"GATEWAY_CLIENT_CA_CERTS;GatewayClient;Unicode"
	"GATEWAY_CLIENT_CLIENT_CERT;GatewayClient;Unicode"
	"GATEWAY_CLIENT_CLIENT_KEY;GatewayClient;Unicode"
	"GATEWAY_CLIENT_CONNECT_TIMEOUT;GatewayClient;Float"
	"GATEWAY_CLIENT_ENV_WHITELIST;GatewayClient;Unicode"
	"GATEWAY_CLIENT_GATEWAY_RETRY_INTERVAL;GatewayClient;Float"
	"GATEWAY_CLIENT_GATEWAY_RETRY_INTERVAL_MAX;GatewayClient;Float"
	"GATEWAY_CLIENT_GATEWAY_RETRY_MAX;GatewayClient;Int"
	"GATEWAY_CLIENT_HEADERS;GatewayClient;Unicode"
	"GATEWAY_CLIENT_HTTP_PWD;GatewayClient;Unicode"
	"GATEWAY_CLIENT_HTTP_USER;GatewayClient;Unicode"
	"GATEWAY_CLIENT_KERNELS_ENDPOINT;GatewayClient;Unicode"
	"GATEWAY_CLIENT_KERNELSPECS_ENDPOINT;GatewayClient;Unicode"
	"GATEWAY_CLIENT_KERNELSPECS_RESOURCE_ENDPOINT;GatewayClient;Unicode"
	"GATEWAY_CLIENT_REQUEST_TIMEOUT;GatewayClient;Float"
	"GATEWAY_CLIENT_URL;GatewayClient;Unicode"
	"GATEWAY_CLIENT_VALIDATE_CERT;GatewayClient;Bool"
	"GATEWAY_CLIENT_WS_URL;GatewayClient;Unicode"
	"TERMINAL_MANAGER_CULL_INACTIVE_TIMEOUT;TerminalManager;Int"
	"TERMINAL_MANAGER_CULL_INTERVAL;TerminalManager;Int"
)


arg_name_from_env_name() {
    if [ -z "$1" ]
    then
        echo "arg_name_from_env_name - missing argument"
    fi
    
    env_name=$1
    env_name_lower=$(echo $env_name | tr '[:upper:]' '[:lower:]')
    env_name_with_dashes=$(echo $env_name_lower | sed 's/_/-/g')
    arg_name_from_env_name_result=$env_name_with_dashes
}

arg_assignment_from_env_var() {
    if [ -z "$1" ]
    then
        echo "arg_assignment_from_env_var - missing argument env_name"
    fi
    
    if [ -z "$2" ]
    then
        echo "arg_assignment_from_env_var - missing argument scope"
    fi

    if [ -z "$3" ]
    then
        echo "arg_assignment_from_env_var - missing argument type"
    fi
    
    env_name=$1
    scope=$2
    type=$3
    
    env_value=${!1}
    
    if [ -z "$env_value" ]
    then
        arg_assignment_from_env_var_result=""
    else
        arg_name_from_env_name $env_name
        if [ "$type" = "Boolean" ] && [ "$scope" = "None" ]
        then
            arg_assignment_from_env_var_result=" --$arg_name_from_env_name_result"
        else
            arg_assignment_from_env_var_result=" --$arg_name_from_env_name_result=$env_value"
        fi
    fi
}

command="jupyter notebook"
for raw_tuple in "${arguments[@]}"
do
    tuple=(${raw_tuple//;/ })
    arg_name=${tuple[0]}
    arg_is_boolean=${tuple[1]}
    
    arg_assignment_from_env_var $arg_name $arg_is_boolean
    command="${command}${arg_assignment_from_env_var_result}"
done

$command